name: Test and publish the ecflow-syntax extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
    - published

jobs:

  test:
    name: Consistency check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Check a new build of ecflow-shell.tmLanguage.json vs. the checked in version
        run: npm run ci_consistency_check

  publish:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/tags/v' )
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
